version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - my-network
  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network
volumes:
  db_data:
networks:
  my-network: